name: Update Hand Crafted Badge

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: badge-update
  cancel-in-progress: true

jobs:
  update-badge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update Badge
        uses: digitaloracle/handcrafted@main
        with:
          auto-commit: 'true'
